#!/bin/bash

REGEX_ISSUE_ID="^(#[0-9]+ [A-Z]+)|Merge|hotfix"
ISSUE_ID_IN_COMMIT=$(echo $(cat "$1") | grep -o -E "$REGEX_ISSUE_ID")

MESSAGE="[commit-msg-hook] Commit message must adhere to this contract: $REGEX_ISSUE_ID. Rename your commit to a valid name and try again."

if [[ -z "$ISSUE_ID_IN_COMMIT" ]]; then
  echo "$MESSAGE"
  exit 1
fi

