#!/bin/bash

REGEX_ISSUE_ID="^([0-9]+-[A-Za-z0-9]+(-[A-Za-z0-9]+)*)|dev|main|release"
ISSUE_ID_IN_BRANCH=$(echo $(git rev-parse --abbrev-ref HEAD) | grep -o -E "$REGEX_ISSUE_ID")

MESSAGE="[pre-commit-hook] Branch name must adhere to this contract: $REGEX_ISSUE_ID. Rename your branch to a valid name and try again."

if [[ -z "$ISSUE_ID_IN_BRANCH" ]]; then
  echo "$MESSAGE"
  exit 1
fi
